-- MySQL Script generated by MySQL Workbench
-- Thu Nov  3 10:22:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_relacional_mascotar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_relacional_mascotar` ;

-- -----------------------------------------------------
-- Schema bd_relacional_mascotar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_relacional_mascotar` DEFAULT CHARACTER SET utf8mb3 ;
USE `bd_relacional_mascotar` ;

-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`direccion` (
  `idDireccion` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `altura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`ciudad` (
  `idciudad` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idciudad`, `direccion_idDireccion`),
  CONSTRAINT `fk_ciudad_direccion1`
    FOREIGN KEY (`direccion_idDireccion`)
    REFERENCES `bd_relacional_mascotar`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ciudad_direccion1_idx` ON `bd_relacional_mascotar`.`ciudad` (`direccion_idDireccion` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`provincia` (
  `idprovincia` INT NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idprovincia`, `direccion_idDireccion`),
  CONSTRAINT `fk_provincia_direccion1`
    FOREIGN KEY (`direccion_idDireccion`)
    REFERENCES `bd_relacional_mascotar`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_provincia_direccion1_idx` ON `bd_relacional_mascotar`.`provincia` (`direccion_idDireccion` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `ciudad_idciudad` INT NOT NULL,
  `provincia_idprovincia` INT NOT NULL,
  `direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`id`, `ciudad_idciudad`, `provincia_idprovincia`, `direccion_idDireccion`),
  CONSTRAINT `fk_usuario_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `bd_relacional_mascotar`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `bd_relacional_mascotar`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_direccion1`
    FOREIGN KEY (`direccion_idDireccion`)
    REFERENCES `bd_relacional_mascotar`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_usuario_ciudad1_idx` ON `bd_relacional_mascotar`.`usuario` (`ciudad_idciudad` ASC);

CREATE INDEX `fk_usuario_provincia1_idx` ON `bd_relacional_mascotar`.`usuario` (`provincia_idprovincia` ASC);

CREATE INDEX `fk_usuario_direccion1_idx` ON `bd_relacional_mascotar`.`usuario` (`direccion_idDireccion` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_carrito_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_relacional_mascotar`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_carrito_usuario1_idx` ON `bd_relacional_mascotar`.`carrito` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dirEnvio` VARCHAR(45) NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`id`, `direccion_idDireccion`),
  CONSTRAINT `fk_orden_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_relacional_mascotar`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_direccion1`
    FOREIGN KEY (`direccion_idDireccion`)
    REFERENCES `bd_relacional_mascotar`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_orden_usuario1_idx` ON `bd_relacional_mascotar`.`orden` (`usuario_id` ASC);

CREATE INDEX `fk_orden_direccion1_idx` ON `bd_relacional_mascotar`.`orden` (`direccion_idDireccion` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`detalle_orden`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`detalle_orden` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `idOrden` INT NOT NULL,
  `orden_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_detalle_orden_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `bd_relacional_mascotar`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_detalle_orden_orden1_idx` ON `bd_relacional_mascotar`.`detalle_orden` (`orden_id` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`especie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`especie` (
  `idEspecie` INT NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`sexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`sexo` (
  `idSexo` INT NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSexo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`estado` (
  `idEstado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`raza` (
  `idRaza` INT NOT NULL,
  `raza` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRaza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`mascota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`mascota` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `especie_idEspecie` INT NOT NULL,
  `sexo_idSexo` INT NOT NULL,
  `estado_idEstado` INT NOT NULL,
  `raza_idRaza` INT NOT NULL,
  `provincia_idprovincia` INT NOT NULL,
  `ciudad_idciudad` INT NOT NULL,
  PRIMARY KEY (`id`, `especie_idEspecie`, `sexo_idSexo`, `estado_idEstado`, `raza_idRaza`, `provincia_idprovincia`, `ciudad_idciudad`),
  CONSTRAINT `fk_mascota_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_relacional_mascotar`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_especie1`
    FOREIGN KEY (`especie_idEspecie`)
    REFERENCES `bd_relacional_mascotar`.`especie` (`idEspecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_sexo1`
    FOREIGN KEY (`sexo_idSexo`)
    REFERENCES `bd_relacional_mascotar`.`sexo` (`idSexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `bd_relacional_mascotar`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_raza1`
    FOREIGN KEY (`raza_idRaza`)
    REFERENCES `bd_relacional_mascotar`.`raza` (`idRaza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_provincia1`
    FOREIGN KEY (`provincia_idprovincia`)
    REFERENCES `bd_relacional_mascotar`.`provincia` (`idprovincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mascota_ciudad1`
    FOREIGN KEY (`ciudad_idciudad`)
    REFERENCES `bd_relacional_mascotar`.`ciudad` (`idciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_mascota_usuario1_idx` ON `bd_relacional_mascotar`.`mascota` (`usuario_id` ASC);

CREATE INDEX `fk_mascota_especie1_idx` ON `bd_relacional_mascotar`.`mascota` (`especie_idEspecie` ASC);

CREATE INDEX `fk_mascota_sexo1_idx` ON `bd_relacional_mascotar`.`mascota` (`sexo_idSexo` ASC) ;

CREATE INDEX `fk_mascota_estado1_idx` ON `bd_relacional_mascotar`.`mascota` (`estado_idEstado` ASC);

CREATE INDEX `fk_mascota_raza1_idx` ON `bd_relacional_mascotar`.`mascota` (`raza_idRaza` ASC);

CREATE INDEX `fk_mascota_provincia1_idx` ON `bd_relacional_mascotar`.`mascota` (`provincia_idprovincia` ASC);

CREATE INDEX `fk_mascota_ciudad1_idx` ON `bd_relacional_mascotar`.`mascota` (`ciudad_idciudad` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`mensajeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`mensajeria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_mensajeria_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `bd_relacional_mascotar`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_mensajeria_usuario1_idx` ON `bd_relacional_mascotar`.`mensajeria` (`usuario_id` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `carrito_id` INT NOT NULL,
  `detalle_orden_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_producto_carrito1`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `bd_relacional_mascotar`.`carrito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_detalle_orden1`
    FOREIGN KEY (`detalle_orden_id`)
    REFERENCES `bd_relacional_mascotar`.`detalle_orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

CREATE INDEX `fk_producto_carrito1_idx` ON `bd_relacional_mascotar`.`producto` (`carrito_id` ASC);

CREATE INDEX `fk_producto_detalle_orden1_idx` ON `bd_relacional_mascotar`.`producto` (`detalle_orden_id` ASC);


-- -----------------------------------------------------
-- Table `bd_relacional_mascotar`.`metodo de pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_relacional_mascotar`.`metodo de pago` (
  `idMetodo_de_pago` INT NOT NULL,
  `metodoPago` VARCHAR(45) NOT NULL,
  `orden_id` INT NOT NULL,
  PRIMARY KEY (`idMetodo_de_pago`, `orden_id`),
  CONSTRAINT `fk_metodo de pago_orden1`
    FOREIGN KEY (`orden_id`)
    REFERENCES `bd_relacional_mascotar`.`orden` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_metodo de pago_orden1_idx` ON `bd_relacional_mascotar`.`metodo de pago` (`orden_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
